#NUMPY

In [1]:
#NUMPY is one of d machine learning library
#numpy is a package. Package is a group of codes dat carry out a task
#Numpy stands for Numerical Python
#Numpy is fast, for so many reasons
#numpy ensures dat every information have a specific data type

In [2]:
#first thing we do while using numpy is 
#1. pip install numpy
#2. import numpy as np(u can use any name but d general convention is np)

In [3]:
#different ways of creating arrays
#how to filter this arrays 
#mathematical concept


#arrays are simply list, collection of information. the data structure related to array is list

In [4]:
#arrays

import numpy as np

In [5]:
d = [1, 3, 6, 5, 4, 24]

In [6]:
type(d)

list

In [7]:
s = np.array(d)

In [8]:
s

array([ 1,  3,  6,  5,  4, 24])

In [9]:
type(s)

numpy.ndarray

In [10]:
s.dtype

dtype('int32')

In [118]:
s.ndim

1

In [12]:
#shape returns d row and column, here we have 6 rows and 0 col

s.shape

(6,)

In [13]:
#size is row multiply by col

s.size

6

In [16]:
#multidimensional array


c = [[2, 4, 7, 8, 1], [1, 3, 8, 2, 9], [9, 6, 3, 2, 5]]

In [17]:
c

[[2, 4, 7, 8, 1], [1, 3, 8, 2, 9], [9, 6, 3, 2, 5]]

In [19]:
np.array(c)

array([[2, 4, 7, 8, 1],
       [1, 3, 8, 2, 9],
       [9, 6, 3, 2, 5]])

In [21]:
u = np.array(c)
u

array([[2, 4, 7, 8, 1],
       [1, 3, 8, 2, 9],
       [9, 6, 3, 2, 5]])

In [119]:
u.ndim

2

In [23]:
u.shape

(3, 5)

In [24]:
u.size

15

In [25]:
u.dtype

dtype('int32')

In [26]:
np.array([1,4,'a'])

array(['1', '4', 'a'], dtype='<U11')

In [27]:
#ways of writing arrays so we dont start afresh
#1. arange

np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
np.arange(2, 14)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [29]:
np.arange(2, 14, 3)

array([ 2,  5,  8, 11])

In [30]:
np.arange(2, 14, 3, dtype = float)

array([ 2.,  5.,  8., 11.])

In [32]:
#np.arange(start, stop, step)

In [33]:
#linspace
#linspace means linearly separable
#this by default takes 50 argument


np.linspace(2, 20)

array([ 2.        ,  2.36734694,  2.73469388,  3.10204082,  3.46938776,
        3.83673469,  4.20408163,  4.57142857,  4.93877551,  5.30612245,
        5.67346939,  6.04081633,  6.40816327,  6.7755102 ,  7.14285714,
        7.51020408,  7.87755102,  8.24489796,  8.6122449 ,  8.97959184,
        9.34693878,  9.71428571, 10.08163265, 10.44897959, 10.81632653,
       11.18367347, 11.55102041, 11.91836735, 12.28571429, 12.65306122,
       13.02040816, 13.3877551 , 13.75510204, 14.12244898, 14.48979592,
       14.85714286, 15.2244898 , 15.59183673, 15.95918367, 16.32653061,
       16.69387755, 17.06122449, 17.42857143, 17.79591837, 18.16326531,
       18.53061224, 18.89795918, 19.26530612, 19.63265306, 20.        ])

In [34]:
#start, stop, return

#the separation here is 4.5

np.linspace(2, 20, 5)

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [47]:
np.linspace(2, 8, 4, dtype = np.int16)

array([2, 4, 6, 8], dtype=int16)

In [36]:
np.linspace(2, 8, dtype = np.int32)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7,
       7, 7, 7, 7, 7, 8])

In [37]:
#np.eye return 2 dimension arrays

np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [38]:
#diag

np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [42]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [51]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [50]:
np.ones(7).dtype.name

'float64'

In [44]:
np.full(7, 9)

array([9, 9, 9, 9, 9, 9, 9])

In [49]:
np.random.rand(7)

array([0.06697025, 0.49085874, 0.68444689, 0.30558787, 0.07428174,
       0.32382175, 0.82396568])

## ARRAY MANIPULATION

In [52]:
np.linspace(2, 20).shape

(50,)

In [53]:
np.linspace(2, 20).reshape(2, 25)

array([[ 2.        ,  2.36734694,  2.73469388,  3.10204082,  3.46938776,
         3.83673469,  4.20408163,  4.57142857,  4.93877551,  5.30612245,
         5.67346939,  6.04081633,  6.40816327,  6.7755102 ,  7.14285714,
         7.51020408,  7.87755102,  8.24489796,  8.6122449 ,  8.97959184,
         9.34693878,  9.71428571, 10.08163265, 10.44897959, 10.81632653],
       [11.18367347, 11.55102041, 11.91836735, 12.28571429, 12.65306122,
        13.02040816, 13.3877551 , 13.75510204, 14.12244898, 14.48979592,
        14.85714286, 15.2244898 , 15.59183673, 15.95918367, 16.32653061,
        16.69387755, 17.06122449, 17.42857143, 17.79591837, 18.16326531,
        18.53061224, 18.89795918, 19.26530612, 19.63265306, 20.        ]])

In [54]:
np.linspace(2, 20).reshape(2, 25).shape

(2, 25)

In [55]:
np.arange(2, 40)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39])

In [56]:
np.arange(2, 40).shape

(38,)

In [57]:
np.arange(2, 40).reshape(2, 19)

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39]])

In [58]:
np.arange(1, 37)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [59]:
np.arange(1, 37).shape

(36,)

In [61]:
np.arange(1, 37).reshape(6,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [62]:
### Transpose: this makes d rows to be d columns and columns to be rows

np.transpose(np.arange(1, 37).reshape(6,6))

array([[ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35],
       [ 6, 12, 18, 24, 30, 36]])

In [68]:
## Stacking: adding arrays ontop of themselves


a = np.array([1,2,3])

b = np.array([[8,9,6], [4,5,6]])

c = np.array([[9,8,31], [7,91,3]])

In [64]:
a

array([1, 2, 3])

In [65]:
b

array([[8, 9, 6],
       [4, 5, 6]])

In [67]:
np.vstack([a,b])

array([[1, 2, 3],
       [8, 9, 6],
       [4, 5, 6]])

In [70]:
np.hstack([b,c])

array([[ 8,  9,  6,  9,  8, 31],
       [ 4,  5,  6,  7, 91,  3]])

## Arithematic operation

In [71]:
a * c

array([[  9,  16,  93],
       [  7, 182,   9]])

In [72]:
o = np.array([2,3,4])
w = np.array([3,4,5])

In [78]:
np.multiply(o,w)

array([ 6, 12, 20])

In [79]:
o * w

array([ 6, 12, 20])

In [74]:
#subtaction method

np.subtract(o,w)

array([-1, -1, -1])

In [75]:
o - w

array([-1, -1, -1])

In [76]:
#addition

np.add(o,w)

array([5, 7, 9])

In [77]:
o + w

array([5, 7, 9])

In [80]:
##Division

np.divide(o,w)

array([0.66666667, 0.75      , 0.8       ])

In [81]:
o / w

array([0.66666667, 0.75      , 0.8       ])

## Aggregate functions

In [82]:
#aggregate fns has to do with a particular array

In [83]:
o

array([2, 3, 4])

In [84]:
o.sum()

9

In [89]:
np.transpose(np.arange(1, 37).reshape(6,6))

array([[ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35],
       [ 6, 12, 18, 24, 30, 36]])

In [86]:
np.transpose(np.arange(1, 37).reshape(6,6)).sum()

666

In [87]:
##note dat axis 0 = col
#axis 1 = row

np.transpose(np.arange(1, 37).reshape(6,6)).sum(axis = 0)

array([ 21,  57,  93, 129, 165, 201])

In [88]:
np.transpose(np.arange(1, 37).reshape(6,6)).sum(axis = 1)

array([ 96, 102, 108, 114, 120, 126])

In [90]:
import pandas as pd
pd.DataFrame(np.transpose(np.arange(1, 37).reshape(6,6)))

0   1   2   3   4   5
0  1   7  13  19  25  31
1  2   8  14  20  26  32
2  3   9  15  21  27  33
3  4  10  16  22  28  34
4  5  11  17  23  29  35
5  6  12  18  24  30  36

In [91]:
#min

np.transpose(np.arange(1, 37).reshape(6,6)).min()

1

In [92]:
np.transpose(np.arange(1, 37).reshape(6,6)).min(axis = 0)

array([ 1,  7, 13, 19, 25, 31])

In [93]:
np.transpose(np.arange(1, 37).reshape(6,6)).min(axis = 1)

array([1, 2, 3, 4, 5, 6])

In [94]:
##max

np.transpose(np.arange(1, 37).reshape(6,6)).max()

36

In [95]:
np.transpose(np.arange(1, 37).reshape(6,6)).max(axis = 0)

array([ 6, 12, 18, 24, 30, 36])

In [96]:
np.transpose(np.arange(1, 37).reshape(6,6)).max(axis = 1)

array([31, 32, 33, 34, 35, 36])

In [97]:
##cumsum: adding and adding to d next

np.transpose(np.arange(1, 37).reshape(6,6)).cumsum()

array([  1,   8,  21,  40,  65,  96,  98, 106, 120, 140, 166, 198, 201,
       210, 225, 246, 273, 306, 310, 320, 336, 358, 386, 420, 425, 436,
       453, 476, 505, 540, 546, 558, 576, 600, 630, 666], dtype=int32)

In [98]:
np.transpose(np.arange(1, 37).reshape(6,6)).cumsum(axis = 0)

array([[  1,   7,  13,  19,  25,  31],
       [  3,  15,  27,  39,  51,  63],
       [  6,  24,  42,  60,  78,  96],
       [ 10,  34,  58,  82, 106, 130],
       [ 15,  45,  75, 105, 135, 165],
       [ 21,  57,  93, 129, 165, 201]], dtype=int32)

In [99]:
np.transpose(np.arange(1, 37).reshape(6,6)).cumsum(axis = 1)

array([[  1,   8,  21,  40,  65,  96],
       [  2,  10,  24,  44,  70, 102],
       [  3,  12,  27,  48,  75, 108],
       [  4,  14,  30,  52,  80, 114],
       [  5,  16,  33,  56,  85, 120],
       [  6,  18,  36,  60,  90, 126]], dtype=int32)

In [100]:
np.transpose(np.arange(1, 37).reshape(6,6)).cumsum(axis = 1).sum()

1701

In [108]:
#mean: mean is average ie sum divided by total number of samples
#median:median is d meddle number when a set of arrays has bin arranged in desending or ascending order


np.transpose(np.arange(1, 37).reshape(6,6)).cumsum(axis = 1).mean()

47.25

In [103]:
np.transpose(np.arange(1, 37).reshape(6,6)).cumsum(axis = 1).mean(axis = 0)

array([  3.5,  13. ,  28.5,  50. ,  77.5, 111. ])

In [104]:
np.transpose(np.arange(1, 37).reshape(6,6)).cumsum(axis = 1).mean(axis = 1)

array([38.5, 42. , 45.5, 49. , 52.5, 56. ])

In [109]:
np.median(np.transpose(np.arange(1, 37)))

18.5

In [111]:
np.transpose(np.arange(1, 37)).std()

10.388294694831615

In [113]:
np.cos(np.transpose(np.arange(1, 37)))

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206,
       -0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281,
        0.64691932, -0.29213881, -0.96260587, -0.74805753,  0.15425145,
        0.91474236,  0.83422336, -0.01327675, -0.84857027, -0.90369221,
       -0.12796369])

In [115]:
np.tan(np.transpose(np.arange(1, 37)))

array([ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,  1.15782128e+00,
       -3.38051501e+00, -2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
       -4.52315659e-01,  6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
        4.63021133e-01,  7.24460662e+00, -8.55993401e-01,  3.00632242e-01,
        3.49391565e+00, -1.13731371e+00,  1.51589471e-01,  2.23716094e+00,
       -1.52749853e+00,  8.85165604e-03,  1.58815308e+00, -2.13489670e+00,
       -1.33526407e-01,  1.17875355e+00, -3.27370380e+00, -2.81429605e-01,
        8.87142844e-01, -6.40533120e+00, -4.41695568e-01,  6.61006041e-01,
       -7.53130148e+01, -6.23498963e-01,  4.73814720e-01,  7.75047091e+00])

In [117]:
np.sin(np.transpose(np.arange(1, 37)))

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525,
        0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175,
        0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162,
       -0.40403765,  0.55142668,  0.99991186,  0.52908269, -0.42818267,
       -0.99177885])